Document: qtwitter
Title: Debian qtwitter Manual
Author: <insert document author here>
Abstract: This manual describes what qtwitter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtwitter/qtwitter.sgml.gz

Format: postscript
Files: /usr/share/doc/qtwitter/qtwitter.ps.gz

Format: text
Files: /usr/share/doc/qtwitter/qtwitter.text.gz

Format: HTML
Index: /usr/share/doc/qtwitter/html/index.html
Files: /usr/share/doc/qtwitter/html/*.html


